# 荧光信号单模态分类配置
# 专注于荧光信号的分类能力

model:
  # 基本参数
  num_classes: 12
  modalities: ['fluorescence']
  
  # 荧光信号配置
  fluorescence_dim: 16
  fluorescence_length: 4000
  
  # 网络结构 - 针对荧光信号优化
  hidden_dims: [512, 256, 128]
  dropout_rate: 0.25
  use_batch_norm: true
  activation: 'relu'
  
  # 融合策略（单模态无需融合）
  fusion_strategy: 'single'

training:
  # 训练参数
  batch_size: 48
  max_epochs: 120
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 4
  
  # 正则化
  gradient_clip_val: 1.0
  early_stopping_patience: 25
  save_every: 10
  
  # 优化器
  optimizer: 'adamw'
  scheduler: 'cosine'

data:
  hdf5_path: 'data/processed/multimodal_data.h5'
  use_cache: true
  cache_size: 1000
  memory_limit: 4.0

experiment:
  name: 'fluorescence_only'
  description: '仅使用荧光信号的分类器'
  save_dir: 'experiments/fluorescence_only'
